name: Build

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.4
      - name: Install bundler
        run: gem install bundler
      - name: Install dependencies
        run: bundle install
      - name: Run lint
        run: rubocop
      - name: Run tests
        run: rspec
