name: Specs

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install bundler
        run: gem install bundler:1.17.3
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: rspec
